import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Stickytop from "./components/Stickytop";
import Footer from "./components/Footer";
import AdvancedNav from "./components/AdvancedNav";
import { Toaster } from "react-hot-toast";
import AuthProvider from "./context/AuthProvider";
import ReduxProvider from "./context/ReduxProvider";
import NavBar from "./components/NavBar";
import Nnavbar from "./components/NnavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Books Roundabouts",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster position="bottom-center" />
        <AuthProvider>
          <ReduxProvider>
            <section>
              <Stickytop />
            </section>
            <section>
              <NavBar />
            </section>
            {children}
            <section>
              <Footer />
            </section>
          </ReduxProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
